/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = 'critical' | 'high' | 'medium' | 'low';
export type IncidentStatus = 'active' | 'blocked' | 'investigating';
export type AttackVector =
  'credential_stuffing' | 'ddos' | 'malware' | 'phishing' | 'supply_chain';

export interface SecurityContract {
  snapshot: SecuritySnapshot;
  stream_event: SecurityStreamEvent;
}
export interface SecuritySnapshot {
  generated_at: number;
  incidents: SecurityIncident[];
  sequence: number;
  summary: SecuritySummary;
  trend: SecurityTrendPoint[];
  vectors: VectorBreakdown[];
}
export interface SecurityIncident {
  blocked_requests: number;
  detected_at: number;
  id: string;
  sequence: number;
  severity: Severity;
  source: GeoLocation;
  status: IncidentStatus;
  target: GeoLocation;
  vector: AttackVector;
}
export interface GeoLocation {
  city: string;
  country: string;
  latitude: number;
  longitude: number;
}
export interface SecuritySummary {
  active_incidents: number;
  attacks_per_minute: number;
  blocked_percent: number;
  critical_incidents: number;
  top_target: string;
}
export interface SecurityTrendPoint {
  attacks: number;
  critical: number;
  label: string;
}
export interface VectorBreakdown {
  count: number;
  vector: AttackVector;
}
export interface SecurityStreamEvent {
  incident: SecurityIncident;
  snapshot: SecuritySnapshot;
}
