import type { SecuritySnapshot } from '../generated.js';

describe('security contract', () => {
  it('models snapshots generated by Rust', () => {
    const snapshot = {
      sequence: 1,
      generated_at: 1,
      incidents: [],
      trend: [],
      vectors: [],
      summary: {
        active_incidents: 0,
        attacks_per_minute: 0,
        blocked_percent: 100,
        critical_incidents: 0,
        top_target: 'None',
      },
    } satisfies SecuritySnapshot;

    expect(snapshot.summary.blocked_percent).toBe(100);
  });
});
